In [1]:
# Step 1 : Import Liberaries

import pandas as pd
import numpy as np

In [5]:
# Step 2 : Load Dataset

df = pd.read_excel("C:/Users/shyam/Downloads/Python/Portfolio Projects/Customer Churn DL/customer_churn_data.xlsx")

In [5]:
# Step 3 : First Look

df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    object
 1   Customer_Name          533 non-null    object
 2   Gender                 536 non-null    object
 3   Age                    536 non-null    float64
 4   State                  531 non-null    object
 5   City                   539 non-null    object
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    object
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    object
 11  Payment_Method         526 non-null    object
 12  Internet_Service       535 non-null    object
 13  Tech_Support           530 non-null    object
 14  Senior_Citizen         534 non-null    object
 15  Dependents             539 non-null    object
 16  Churn                  538 non-null    object
 17  Last_Interaction_Date  539 non-null    object
dtypes: float64(4), object(14)
memory usage: 76.3+ KB

In [7]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [8]:
df.shape

(542, 18)

In [9]:
# Step 4 : Check Missing Vlues

df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

In [10]:
# Step 5 : Check Duplicates Records

df.duplicated().sum()

7

In [11]:
# Remove Duplicates

df.drop_duplicates(inplace = True)

In [12]:
df.shape

(535, 18)

In [13]:
# Step 6 : Replace Dirty Values

df.replace(['N/A','NULL','',' '],np.nan,inplace = True)

In [14]:
df.isnull().sum()

Customer_ID               0
Customer_Name             8
Gender                    5
Age                       6
State                    10
City                      5
Tenure_Months             7
Subscription_Type        11
Monthly_Charges          12
Total_Charges             8
Contract_Type             3
Payment_Method           15
Internet_Service          6
Tech_Support             11
Senior_Citizen            7
Dependents                2
Churn                     3
Last_Interaction_Date     2
dtype: int64

In [15]:
# Step 7 : Remove Extra Spaces

df = df.apply(lambda x:x.str.strip() if x.dtype == 'object' else x)

In [16]:
# value counts

df["Subscription_Type"].value_counts()

Subscription_Type
Premium     184
Standard    169
Basic       167
basic         2
BASIC         2
Name: count, dtype: int64

In [17]:
df.dtypes

Customer_ID               object
Customer_Name             object
Gender                    object
Age                      float64
State                     object
City                      object
Tenure_Months            float64
Subscription_Type         object
Monthly_Charges          float64
Total_Charges            float64
Contract_Type             object
Payment_Method            object
Internet_Service          object
Tech_Support              object
Senior_Citizen            object
Dependents                object
Churn                     object
Last_Interaction_Date     object
dtype: object

In [18]:
# Step 8 : Proper Case

df["Customer_Name"] = df["Customer_Name"].str.title()
df["Gender"] = df["Gender"].str.title()
df["State"] = df["State"].str.title()
df["City"] = df["City"].str.title()
df["Subscription_Type"] = df["Subscription_Type"].str.title()
df["Contract_Type"] = df["Contract_Type"].str.title()
df["Payment_Method"] = df["Payment_Method"].str.title()
df["Internet_Service"] = df["Internet_Service"].str.title()
df["Tech_Support"] = df["Tech_Support"].str.title()
df["Senior_Citizen"] = df["Senior_Citizen"].str.title()
df["Dependents"] = df["Dependents"].str.title()
df["Churn"] = df["Churn"].str.title()

In [19]:
df["Subscription_Type"].value_counts()

Subscription_Type
Premium     184
Basic       171
Standard    169
Name: count, dtype: int64

In [20]:
# Step 9 : Convert Numeric Columns

cols = ["Age","Tenure_Months","Monthly_Charges","Total_Charges"]

for x in cols :
    df[x] = pd.to_numeric(df[x],errors ="coerce" )

In [21]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  529.000000     528.000000       523.000000     527.000000
mean    44.328922      36.518939      1329.967285   49739.683890
std     18.635396      20.659332       713.450173   41633.677902
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       757.420000   18818.270000
50%     44.000000      38.000000      1295.880000   40649.600000
75%     57.000000      54.000000      1879.020000   75126.770000
max    165.000000      72.000000      2492.510000  171429.830000

In [22]:
# Step 10 : Remove Invalid Age

df = df[(df["Age"]>=18) & (df["Age"]<=100)]

In [23]:
# Step 11 : Remove Negative Charges

df = df[df["Monthly_Charges"]>=0]
df = df[df["Total_Charges"]>=0]

In [24]:
df.shape

(492, 18)

In [25]:
# Step 12 : Convert Date

df["Last_Interaction_Date"] = pd.to_datetime (df["Last_Interaction_Date"],errors ="coerce")

In [26]:
# Step 13 : Fill Missing Value

df["Tech_Support"].fillna("No",inplace = True)
df["Payment_Method"].fillna("Unknown",inplace =True)
df["Monthly_Charges"].fillna(df["Monthly_Charges"].mean(),inplace =True)
df["Tenure_Months"].fillna(df["Tenure_Months"].mean(),inplace =True)
df["Age"].fillna(df["Age"].mean(),inplace =True)

In [27]:
df["Last_Interaction_Date"].fillna(df["Last_Interaction_Date"].median(),inplace =True)

In [28]:
# Step 14 : Feature Engineering

# Customer Lifetime Value

df["Customer_Value"] = df["Monthly_Charges"] * df["Tenure_Months"]

In [29]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,Upi,Fiber,Yes,No,Yes,No,2025-12-10,93627.08
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2025-08-24,7215.39
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-02-04,1884.12
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,Upi,Dsl,Yes,No,No,No,2025-08-24,140618.10
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-08-24,125182.26

In [30]:
# Monthly Revenue

df["Monthly_Revenue"] = df["Monthly_Charges"]

In [31]:
# Tenure Group "0-12","13-24","25-48","49-72"

bins = [0,12,24,48,72]
labels = ["0-12 month","13-24 month","25-48 month","49-72 month"]
df["Tenure_Group"] = pd.cut(df["Tenure_Months"],bins = bins, labels = labels)

In [32]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Upi,Fiber,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72 month
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,Debit Card,5G,No,No,No,Yes,2025-08-24,7215.39,555.03,13-24 month
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Debit Card,Cable,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12 month
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,Upi,Dsl,Yes,No,No,No,2025-08-24,140618.10,2008.83,49-72 month
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Cash,Cable,Yes,Yes,Yes,No,2025-08-24,125182.26,2196.18,49-72 month

In [33]:
# Senior Citizen Flag

df["Senior_Flag"] = np.where(df["Age"]>=60,"Senior","Adult")

In [34]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Fiber,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72 month,Adult
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,5G,No,No,No,Yes,2025-08-24,7215.39,555.03,13-24 month,Adult
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Cable,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12 month,Adult
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,Dsl,Yes,No,No,No,2025-08-24,140618.10,2008.83,49-72 month,Adult
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Cable,Yes,Yes,Yes,No,2025-08-24,125182.26,2196.18,49-72 month,Senior

In [35]:
# Churn Flag

df["Churn_Flag"] = df["Churn"].map({"Yes":1,"No":0})

In [36]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag,Churn_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72 month,Adult,0.0
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,No,No,No,Yes,2025-08-24,7215.39,555.03,13-24 month,Adult,1.0
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12 month,Adult,0.0
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,Yes,No,No,No,2025-08-24,140618.10,2008.83,49-72 month,Adult,0.0
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Yes,Yes,Yes,No,2025-08-24,125182.26,2196.18,49-72 month,Senior,0.0

In [37]:
# Final Check

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 492 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    object
 1   Customer_Name          487 non-null    object
 2   Gender                 488 non-null    object
 3   Age                    492 non-null    float64
 4   State                  485 non-null    object
 5   City                   487 non-null    object
 6   Tenure_Months          492 non-null    float64
 7   Subscription_Type      486 non-null    object
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    object
 11  Payment_Method         492 non-null    object
 12  Internet_Service       486 non-null    object
 13  Tech_Support           492 non-null    object
 14  Senior_Citizen         486 non-null    object
 15  Dependents             491 non-null    object
 16  Churn                  490 non-null    object
 17  Last_Interaction_Date  492 non-null    datetime64[ns]
 18  Customer_Value         492 non-null    float64
 19  Monthly_Revenue        492 non-null    float64
 20  Tenure_Group           492 non-null    category
 21  Senior_Flag            492 non-null    object
 22  Churn_Flag             490 non-null    float64
dtypes: category(1), datetime64[ns](1), float64(7), object(14)
memory usage: 89.1+ KB

In [38]:
df.describe()

,Age,Tenure_Months,Monthly_Charges,Total_Charges,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Churn_Flag
count,492.000000,492.000000,492.000000,492.000000,492,492.000000,492.000000,490.000000
mean,43.191057,36.059548,1359.222033,50363.987561,2025-09-05 13:10:14.634146304,50231.467233,1359.222033,0.236735
min,18.000000,1.000000,302.540000,354.120000,2025-01-01 00:00:00,379.700000,302.540000,0.000000
25%,30.000000,19.000000,762.940000,19129.100000,2025-08-24 00:00:00,19125.137500,762.940000,0.000000
50%,43.000000,37.000000,1308.510000,40668.695000,2025-08-24 00:00:00,40701.195000,1308.510000,0.000000
75%,56.000000,53.000000,1889.437500,74393.410000,2025-08-24 00:00:00,74097.160000,1889.437500,0.000000
max,70.000000,72.000000,2492.510000,171429.830000,2026-12-06 00:00:00,171658.830000,2492.510000,1.000000
std,15.401619,20.360662,653.133221,39760.135287,NaN,39647.442978,653.133221,0.425513

In [39]:
df.isnull().sum()

Customer_ID              0
Customer_Name            5
Gender                   4
Age                      0
State                    7
City                     5
Tenure_Months            0
Subscription_Type        6
Monthly_Charges          0
Total_Charges            0
Contract_Type            2
Payment_Method           0
Internet_Service         6
Tech_Support             0
Senior_Citizen           6
Dependents               1
Churn                    2
Last_Interaction_Date    0
Customer_Value           0
Monthly_Revenue          0
Tenure_Group             0
Senior_Flag              0
Churn_Flag               2
dtype: int64

In [42]:
df["Customer_Name"].fillna("Unknown",inplace =True)

In [44]:
df[df["State"].isna()]

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag,Churn_Flag
25,C1025,Anjali Mehta,Male,70.0,NaN,Delhi,42.0,NaN,1516.78,64151.76,...,Yes,Yes,Yes,No,2026-06-03,63704.76,1516.78,25-48 month,Senior,0.0
108,C1108,Vikas Yadav,Male,70.0,NaN,Ahmedabad,10.0,Standard,314.10,3107.00,...,Yes,Yes,No,No,2025-08-24,3141.00,314.10,0-12 month,Senior,0.0
113,C1113,Anjali Mehta,Male,43.0,NaN,Pune,71.0,Standard,2417.73,171429.83,...,No,No,No,No,2025-08-24,171658.83,2417.73,49-72 month,Adult,0.0
148,C1148,Vikas Yadav,Male,59.0,NaN,Bengaluru,47.0,Basic,355.44,17130.68,...,No,No,Yes,No,2025-08-24,16705.68,355.44,25-48 month,Adult,0.0
177,C1177,Pooja Singh,Male,53.0,NaN,Ahmedabad,23.0,Basic,519.20,11447.60,...,Yes,No,No,No,2026-09-03,11941.60,519.20,13-24 month,Adult,0.0
473,C1473,Sneha Jain,Female,36.0,NaN,Surat,49.0,Basic,2485.13,121892.37,...,Yes,No,Yes,No,2025-08-24,121771.37,2485.13,49-72 month,Adult,0.0
509,C1509,Rahul Singh,Male,26.0,NaN,Surat,38.0,Basic,759.70,29247.60,...,Yes,No,No,No,2026-02-01,28868.60,759.70,25-48 month,Adult,0.0

In [41]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'State', 'City',
       'Tenure_Months', 'Subscription_Type', 'Monthly_Charges',
       'Total_Charges', 'Contract_Type', 'Payment_Method', 'Internet_Service',
       'Tech_Support', 'Senior_Citizen', 'Dependents', 'Churn',
       'Last_Interaction_Date', 'Customer_Value', 'Monthly_Revenue',
       'Tenure_Group', 'Senior_Flag', 'Churn_Flag'],
      dtype='object')

In [47]:
df.loc[(df['City'] == 'Delhi') & (df['State'].isna()), 'State'] = 'Delhi'
df.loc[(df['City'] == 'Ahmedabad') & (df['State'].isna()), 'State'] = 'Gujarat'
df.loc[(df['City'] == 'Pune') & (df['State'].isna()), 'State'] = 'Maharashtra'
df.loc[(df['City'] == 'Bengaluru') & (df['State'].isna()), 'State'] = 'Karnataka'
df.loc[(df['City'] == 'Surat') & (df['State'].isna()), 'State'] = 'Gujarat'

In [49]:
df[df["City"].isna()]

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag,Churn_Flag
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Yes,Yes,Yes,No,2025-08-24,125182.26,2196.18,49-72 month,Senior,0.0
31,C1031,Abhishek Jaiswal,Male,37.0,Up,NaN,23.0,Premium,1555.38,35431.74,...,Yes,No,No,Yes,2025-08-24,35773.74,1555.38,13-24 month,Adult,1.0
147,C1147,Vikas Yadav,NaN,62.0,Delhi,NaN,42.0,Basic,2492.51,104747.42,...,No,Yes,No,No,2025-08-24,104685.42,2492.51,25-48 month,Senior,0.0
437,C1437,Sneha Jain,Female,56.0,Up,NaN,2.0,Premium,873.54,1712.08,...,No,No,No,No,2025-02-05,1747.08,873.54,0-12 month,Adult,0.0
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Yes,Yes,Yes,No,2025-08-24,125182.26,2196.18,49-72 month,Senior,0.0

In [52]:
df.loc[(df["State"]=="Delhi")&(df["City"].isna()),"City"] = "Delhi"

In [55]:
df[df["Gender"].isna()]

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag,Churn_Flag
18,C1018,Amit Sharma,NaN,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,...,Yes,No,Yes,No,2025-04-06,111759.36,2328.32,25-48 month,Adult,0.0
147,C1147,Vikas Yadav,NaN,62.0,Delhi,Delhi,42.0,Basic,2492.51,104747.42,...,No,Yes,No,No,2025-08-24,104685.42,2492.51,25-48 month,Senior,0.0
232,C1232,Rahul Singh,NaN,46.0,Gujarat,Ahmedabad,60.0,Premium,389.88,23043.80,...,No,No,Yes,No,2025-08-24,23392.80,389.88,49-72 month,Adult,0.0
456,C1456,Amit Sharma,NaN,47.0,Karnataka,Bengaluru,24.0,Premium,1752.46,41573.04,...,No,No,Yes,No,2025-08-24,42059.04,1752.46,13-24 month,Adult,0.0

In [56]:
df["Gender"].fillna("Male",inplace =True)

In [59]:
df.isnull().sum()

Customer_ID              0
Customer_Name            0
Gender                   0
Age                      0
State                    0
City                     2
Tenure_Months            0
Subscription_Type        6
Monthly_Charges          0
Total_Charges            0
Contract_Type            2
Payment_Method           0
Internet_Service         6
Tech_Support             0
Senior_Citizen           6
Dependents               1
Churn                    2
Last_Interaction_Date    0
Customer_Value           0
Monthly_Revenue          0
Tenure_Group             0
Senior_Flag              0
Churn_Flag               2
dtype: int64

In [60]:
df.dropna(inplace = True)

In [61]:
df.isnull().sum()

Customer_ID              0
Customer_Name            0
Gender                   0
Age                      0
State                    0
City                     0
Tenure_Months            0
Subscription_Type        0
Monthly_Charges          0
Total_Charges            0
Contract_Type            0
Payment_Method           0
Internet_Service         0
Tech_Support             0
Senior_Citizen           0
Dependents               0
Churn                    0
Last_Interaction_Date    0
Customer_Value           0
Monthly_Revenue          0
Tenure_Group             0
Senior_Flag              0
Churn_Flag               0
dtype: int64

In [62]:
# Step 15 : CSV Clean Dataset

# CSV is Saved in Jupyter Notebook

df.to_csv("Clean_Churn_Data.csv",index = False)

In [63]:
# CSV is Saved in Specific Location

df.to_csv(r"C:\Users\shyam\Downloads\Python\Portfolio Projects\Customer Churn DL\Clean_Churn_Data.csv",index = False)

In [64]:
# Step 16 : Export into MySQL

from sqlalchemy import create_engine
from urllib.parse import quote_plus

# MYSQL connection

username = "root" # default user
password = quote_plus("51016@saa")   # encode special characters - because i have "@" in my password - password set during installation
host = "localhost"  # if running locally
port = "3306"    # default MYSQL port
database = "customer_churn"   # database created in MYSQL


engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")


# Load DataFrame into MYSQL

df.to_sql(
name = "customer",    # name = table name i chose
con = engine,
if_exists = "replace",
index = False)

471